# 菜单配置
[[main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = '<i class="fa fa-archive faa-wrench"></i>'
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "归档"
    url = "/posts/"
    title = ""
    weight = 1
[[main]]
    identifier = "tags"
    pre = '<i class="fa fa-tag faa-wrench"></i>'
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
[[main]]
    identifier = "categories"
    pre = '<i class="fa fa-folder-open faa-wrench"></i>'
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
[[main]]
    identifier = "series"
    pre = '<i class="fas fa-object-group"></i>'
    post = ""
    name = "系列"
    url = "/series/"
    title = ""
    weight = 4
[[main]]
    identifier = "about"
    pre = '<i class="fa fa-info-circle faa-wrench"></i>'
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 5
[[main]]
    identifier = "links"
    pre = '<i class="fa fa-user-friends faa-wrench"></i>'
    post = ""
    name = "友人帐"
    url = "/links/"
    title = ""
    weight = 6
# [[main]]
#     identifier = "gitlab"
#     pre = "<i class='fab fa-gitlab fa-fw'></i>"
#     post = ""
#     name = ""
#     url = "https://gitlab.com/GinShio"
#     title = "GitLab"
#     weight = 7
