# 网站描述
description = "iris | GinShio 的个人博客"
# 网站关键词
keywords = ["GinShio", "Programming", "Linux", "C++", "Compiler", "GPU"]

# 应用图标配置
[app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "iris"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10 磁贴颜色
    tileColor = "#da532c"

# 搜索配置
[search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia", "fuse")
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # 最大结果数目
    maxResultLength = 10
    # 结果内容片段长度
    snippetLength = 50
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [search.algolia]
        index = "ginshio_blog"
        appID = "ABF13CGNA0"
        searchKey = "51cf3425aba132c091b477c3d5e06eea"
    [search.fuse]
        # https://fusejs.io/api/options.html
        isCaseSensitive = false
        minMatchCharLength = 2
        findAllMatches = false
        location = 0
        threshold = 0.1
        distance = 100
        ignoreLocation = true
        useExtendedSearch = false
        ignoreFieldNorm = false
    [search.pagefind]
        # https://pagefind.app/docs/search-config/#available-options
        # run `npx pagefind --site $YOUR_PUBLIC_DIR` after site build to create pagefind index
        termFrequency = 1.0
        pageLength = 0.75
        termSimilarity = 1.0
        termSaturation = 1.4

# 主页信息设置
[home]
    # RSS 文章数目
    rss = 12
    # 主页个人信息
    [home.profile]
        enable = true
        # Gravatar 邮箱，用于优先在主页显示的头像
        gravatarEmail = ""
        # 主页显示头像的 URL
        avatarURL = "/avatar.webp"
        # 主页显示的网站标题 (支持 HTML 格式)
        title = "GinShio"
        # 主页显示的网站副标题
        subtitle = "過去一直去，未來一直來，只有現在……"
        # 是否为副标题显示打字机动画
        typeit = true
        # 是否显示社交账号
        social = true
        # 免责声明 (支持 HTML 格式)
        disclaimer = ""
    # 主页文章列表
    [home.posts]
        enable = true
        # 主页每页显示文章数量
        paginate = 12

# 主页的社交信息设置
[social]
    Angellist = ""
    Bandcamp = ""
    Behance = ""
    Bilibili = "5091427"
    Bitbucket = ""
    BuyMeACoffee = ""
    Codepen = ""
    Deviantart = ""
    Devto = ""
    Douban = ""
    Dribbble = ""
    Email = "ginshio78@gmail.com"
    Facebook = ""
    Fivehundredpx = ""
    Flickr = ""
    Foursquare = ""
    FreeCodeCamp = ""
    Gitea = ""
    GitHub = "GinShio"
    Gitlab = "GinShio"
    Goodreads = ""
    Googlescholar = ""
    Hackernews = ""
    Instagram = ""
    Jsfiddle = ""
    Keybase = ""
    Kickstarter = ""
    Ko-Fi = ""
    Lastfm = ""
    Liberapay = ""
    Linkedin = ""
    Linktree = ""
    Matrix = ""
    Medium = ""
    Mix = ""
    Odnoklassniki = ""
    ORCID = ""
    Patreon = ""
    Paypal = ""
    Pinterest = ""
    QQ = ""
    QQGroup = ""
    Quora = ""
    Reddit = ""
    Researchgate = ""
    RSS = true
    Skype = ""
    Slidershare = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Stackoverflow = ""
    Steam = "GinShio"
    Strava = ""
    Telegram = ""
    Thingiverse = ""
    Tumblr = ""
    Twitch = ""
    Twitter = ""
    Vine = ""
    VK = ""
    Weibo = ""
    Whatsapp = ""
    Wordpress = ""
    Xing = ""
    XMPP = ""
    Youtubechannel = ""
    Youtubecustom = ""
    Youtubelegacy = ""
    Zhihu = ""
    [social.Diaspora]
        #id = "@xxxx"
        #prefix = "https://yyyy/"

# 赞助设置
[sponsor]
    enable = false
    bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
    link = "https://github.com/sponsors/HEIGE-PCloud"
    # custom = "<a href=\"https://www.buymeacoffee.com/PCloud\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"
